[build]
  command = "npm run build"
  publish = "/media/faizanasghar43/929e8658-4567-4c64-9f5c-dabf56bb6810/home/muhammad/Ghost-main/Ghost-Installation/content"

[[redirects]]
  from = "/*"
  to = "/{splat}"
  status = 200

[[redirects]]
  from = "/ghost"
  to = "/ghost/"
  status = 301

[[redirects]]
  from = "/ghost/*"
  to = "https://yourghostsite.com/ghost/:splat"
  status = 301

